-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.farms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text,
  owner_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT farms_pkey PRIMARY KEY (id),
  CONSTRAINT farms_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.farm_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'worker'::text CHECK (role = ANY (ARRAY['owner'::text, 'manager'::text, 'worker'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT farm_members_pkey PRIMARY KEY (id),
  CONSTRAINT farm_members_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT farm_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT farm_members_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.animals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  tag_number text NOT NULL,
  breed text,
  sex text CHECK (sex = ANY (ARRAY['male'::text, 'female'::text])),
  purchase_date date NOT NULL,
  purchase_weight_kg numeric NOT NULL,
  purchase_price numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'sold'::text, 'sick'::text, 'removed'::text, 'dead'::text])),
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  species_id uuid NOT NULL,
  breed_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  acquisition_method text NOT NULL DEFAULT 'purchased'::text CHECK (acquisition_method = ANY (ARRAY['purchased'::text, 'bred_in_house'::text])),
  sold_at date,
  CONSTRAINT animals_pkey PRIMARY KEY (id),
  CONSTRAINT animals_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT animals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT animals_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id),
  CONSTRAINT animals_breed_id_fkey FOREIGN KEY (breed_id) REFERENCES public.animal_breeds(id)
);
CREATE TABLE public.weight_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  weight_kg numeric NOT NULL,
  recorded_at date NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weight_records_pkey PRIMARY KEY (id),
  CONSTRAINT weight_records_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT weight_records_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT weight_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.feed_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  name text NOT NULL,
  cost_per_kg numeric NOT NULL DEFAULT 0,
  protein_percentage numeric,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  species_id uuid,
  dry_matter_percentage numeric,
  category text NOT NULL DEFAULT 'other'::text CHECK (category = ANY (ARRAY['concentrate'::text, 'roughage'::text, 'silage'::text, 'hay'::text, 'supplement'::text, 'mineral'::text, 'mixed_ration'::text, 'other'::text])),
  description text,
  crude_fiber_percentage numeric,
  energy_me_mj_per_kg numeric,
  fat_percentage numeric,
  calcium_percentage numeric,
  phosphorus_percentage numeric,
  low_stock_threshold_kg numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT feed_types_pkey PRIMARY KEY (id),
  CONSTRAINT feed_types_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feed_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT feed_types_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id)
);
CREATE TABLE public.feed_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  feed_type_id uuid,
  quantity_kg numeric NOT NULL,
  feeding_date date NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feed_records_pkey PRIMARY KEY (id),
  CONSTRAINT feed_records_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feed_records_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT feed_records_feed_type_id_fkey FOREIGN KEY (feed_type_id) REFERENCES public.feed_types(id),
  CONSTRAINT feed_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.market_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  price_per_kg numeric NOT NULL CHECK (price_per_kg > 0::numeric),
  recorded_at date NOT NULL,
  source text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  species_id uuid,
  market_source_id uuid,
  currency text NOT NULL,
  price_basis text NOT NULL CHECK (price_basis = ANY (ARRAY['live_weight'::text, 'carcass_weight'::text, 'per_head'::text])),
  quality_grade text,
  weight_min_kg numeric,
  weight_max_kg numeric,
  CONSTRAINT market_prices_pkey PRIMARY KEY (id),
  CONSTRAINT market_prices_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT market_prices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT market_prices_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id),
  CONSTRAINT market_prices_market_source_id_fkey FOREIGN KEY (market_source_id) REFERENCES public.market_sources(id)
);
CREATE TABLE public.sales_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  sale_weight_kg numeric NOT NULL,
  price_per_kg numeric NOT NULL,
  total_amount numeric NOT NULL,
  sold_at date NOT NULL,
  buyer_name text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  species_id uuid,
  buyer_contact text,
  price_basis text NOT NULL DEFAULT 'live_weight'::text CHECK (price_basis = ANY (ARRAY['live_weight'::text, 'carcass_weight'::text, 'per_head'::text])),
  currency text NOT NULL DEFAULT 'USD'::text,
  gross_amount numeric NOT NULL DEFAULT 0,
  purchase_cost numeric NOT NULL DEFAULT 0,
  feed_cost numeric NOT NULL DEFAULT 0,
  health_cost numeric NOT NULL DEFAULT 0,
  other_cost numeric NOT NULL DEFAULT 0,
  total_cost numeric NOT NULL DEFAULT 0,
  net_profit numeric,
  profit_margin_percentage numeric,
  market_price_id uuid,
  prediction_id uuid,
  payment_status text NOT NULL DEFAULT 'paid'::text CHECK (payment_status = ANY (ARRAY['paid'::text, 'partially_paid'::text, 'unpaid'::text])),
  sale_status text NOT NULL DEFAULT 'completed'::text CHECK (sale_status = ANY (ARRAY['completed'::text, 'voided'::text, 'pending_payment'::text, 'cancelled'::text])),
  prediction_accuracy text NOT NULL DEFAULT 'not_linked'::text CHECK (prediction_accuracy = ANY (ARRAY['accurate'::text, 'close'::text, 'overestimated'::text, 'underestimated'::text, 'not_linked'::text])),
  market_comparison_percentage numeric,
  voided_at timestamp with time zone,
  voided_by uuid,
  void_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_records_pkey PRIMARY KEY (id),
  CONSTRAINT sales_records_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT sales_records_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT sales_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT sales_records_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id),
  CONSTRAINT sales_records_market_price_id_fkey FOREIGN KEY (market_price_id) REFERENCES public.market_prices(id),
  CONSTRAINT sales_records_prediction_id_fkey FOREIGN KEY (prediction_id) REFERENCES public.selling_predictions(id),
  CONSTRAINT sales_records_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES auth.users(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid,
  alert_type text NOT NULL,
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  title text NOT NULL,
  message text NOT NULL,
  resolved boolean NOT NULL DEFAULT false,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text])),
  detected_metric text,
  expected_value numeric,
  actual_value numeric,
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  source text NOT NULL DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['rule_based'::text, 'statistical'::text, 'ml_model'::text, 'manual'::text])),
  engine_version text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolution_notes text,
  last_detected_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT alerts_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  email text NOT NULL,
  last_active_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.animal_species (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT animal_species_pkey PRIMARY KEY (id)
);
CREATE TABLE public.animal_breeds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  species_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT animal_breeds_pkey PRIMARY KEY (id),
  CONSTRAINT animal_breeds_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id)
);
CREATE TABLE public.pens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  name text NOT NULL,
  species_id uuid,
  capacity integer,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'maintenance'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pens_pkey PRIMARY KEY (id),
  CONSTRAINT pens_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT pens_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id)
);
CREATE TABLE public.animal_pen_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  pen_id uuid NOT NULL,
  started_at date NOT NULL DEFAULT CURRENT_DATE,
  ended_at date,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT animal_pen_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT animal_pen_assignments_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT animal_pen_assignments_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT animal_pen_assignments_pen_id_fkey FOREIGN KEY (pen_id) REFERENCES public.pens(id)
);
CREATE TABLE public.feeding_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  pen_id uuid,
  feed_type_id uuid,
  feeding_method text NOT NULL CHECK (feeding_method = ANY (ARRAY['individual'::text, 'pen_group'::text, 'custom_group'::text])),
  quantity_kg numeric NOT NULL CHECK (quantity_kg > 0::numeric),
  feeding_date date NOT NULL,
  allocation_method text NOT NULL DEFAULT 'equal_per_animal'::text CHECK (allocation_method = ANY (ARRAY['equal_per_animal'::text, 'by_weight_percentage'::text, 'manual'::text])),
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feeding_events_pkey PRIMARY KEY (id),
  CONSTRAINT feeding_events_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feeding_events_pen_id_fkey FOREIGN KEY (pen_id) REFERENCES public.pens(id),
  CONSTRAINT feeding_events_feed_type_id_fkey FOREIGN KEY (feed_type_id) REFERENCES public.feed_types(id),
  CONSTRAINT feeding_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.feeding_event_animals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  feeding_event_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  allocated_quantity_kg numeric NOT NULL CHECK (allocated_quantity_kg >= 0::numeric),
  allocated_cost numeric NOT NULL DEFAULT 0 CHECK (allocated_cost >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feeding_event_animals_pkey PRIMARY KEY (id),
  CONSTRAINT feeding_event_animals_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feeding_event_animals_feeding_event_id_fkey FOREIGN KEY (feeding_event_id) REFERENCES public.feeding_events(id),
  CONSTRAINT feeding_event_animals_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id)
);
CREATE TABLE public.health_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  event_date date NOT NULL,
  event_type text NOT NULL DEFAULT 'observation'::text CHECK (event_type = ANY (ARRAY['observation'::text, 'illness'::text, 'injury'::text, 'treatment'::text, 'vaccination'::text, 'deworming'::text, 'inspection'::text, 'recovery'::text, 'other'::text])) NOT VALI),
  severity text NOT NULL DEFAULT 'low'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  title text NOT NULL,
  notes text,
  treatment text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'monitoring'::text, 'under_treatment'::text, 'recovering'::text, 'resolved'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  observed_at date NOT NULL,
  symptoms text,
  diagnosis_note text,
  treatment_given text,
  treated_by text,
  recovery_notes text,
  resolved_at timestamp with time zone,
  CONSTRAINT health_events_pkey PRIMARY KEY (id),
  CONSTRAINT health_events_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT health_events_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT health_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.feed_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  feed_type_id uuid NOT NULL,
  batch_number text,
  supplier_name text,
  purchase_date date NOT NULL,
  expiry_date date,
  initial_quantity_kg numeric NOT NULL CHECK (initial_quantity_kg > 0::numeric),
  unit_cost numeric NOT NULL CHECK (unit_cost >= 0::numeric),
  total_cost numeric DEFAULT (initial_quantity_kg * unit_cost),
  storage_location text,
  nutrition_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feed_batches_pkey PRIMARY KEY (id),
  CONSTRAINT feed_batches_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feed_batches_feed_type_id_fkey FOREIGN KEY (feed_type_id) REFERENCES public.feed_types(id),
  CONSTRAINT feed_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.feed_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  feed_type_id uuid NOT NULL,
  feed_batch_id uuid,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['purchase'::text, 'feeding'::text, 'adjustment_in'::text, 'adjustment_out'::text, 'spoilage'::text, 'transfer_in'::text, 'transfer_out'::text, 'return'::text])),
  quantity_kg numeric NOT NULL CHECK (quantity_kg <> 0::numeric),
  unit_cost numeric,
  total_cost numeric,
  movement_date date NOT NULL,
  reference_type text,
  reference_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feed_movements_pkey PRIMARY KEY (id),
  CONSTRAINT feed_movements_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT feed_movements_feed_type_id_fkey FOREIGN KEY (feed_type_id) REFERENCES public.feed_types(id),
  CONSTRAINT feed_movements_feed_batch_id_fkey FOREIGN KEY (feed_batch_id) REFERENCES public.feed_batches(id),
  CONSTRAINT feed_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.market_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  name text NOT NULL,
  source_type text NOT NULL DEFAULT 'other'::text CHECK (source_type = ANY (ARRAY['auction'::text, 'abattoir'::text, 'butcher'::text, 'private_buyer'::text, 'market_board'::text, 'online'::text, 'other'::text])),
  location text,
  contact_name text,
  contact_phone text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_sources_pkey PRIMARY KEY (id),
  CONSTRAINT market_sources_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT market_sources_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.prediction_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  run_type text NOT NULL DEFAULT 'manual'::text CHECK (run_type = ANY (ARRAY['manual'::text, 'scheduled'::text, 'single_animal'::text])),
  status text NOT NULL DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  created_by uuid,
  engine_version text NOT NULL DEFAULT 'selling-predictions-v1'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  CONSTRAINT prediction_runs_pkey PRIMARY KEY (id),
  CONSTRAINT prediction_runs_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT prediction_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.selling_predictions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  prediction_run_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  species_id uuid,
  current_weight_kg numeric,
  average_daily_gain_kg numeric,
  current_market_price numeric,
  best_window_days integer NOT NULL DEFAULT 0,
  best_sell_date date,
  predicted_weight_kg numeric,
  expected_revenue numeric,
  expected_total_cost numeric,
  expected_profit numeric,
  recommendation text NOT NULL CHECK (recommendation = ANY (ARRAY['SELL_NOW'::text, 'HOLD'::text, 'WATCH'::text, 'INSPECT_BEFORE_SELLING'::text, 'NOT_READY'::text])),
  confidence_score numeric NOT NULL DEFAULT 0 CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  confidence_label text NOT NULL DEFAULT 'Low'::text CHECK (confidence_label = ANY (ARRAY['High'::text, 'Medium'::text, 'Low'::text])),
  explanation text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT selling_predictions_pkey PRIMARY KEY (id),
  CONSTRAINT selling_predictions_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT selling_predictions_prediction_run_id_fkey FOREIGN KEY (prediction_run_id) REFERENCES public.prediction_runs(id),
  CONSTRAINT selling_predictions_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id),
  CONSTRAINT selling_predictions_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id)
);
CREATE TABLE public.health_assessment_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  run_type text NOT NULL DEFAULT 'manual'::text CHECK (run_type = ANY (ARRAY['manual'::text, 'scheduled'::text, 'single_animal'::text])),
  status text NOT NULL DEFAULT 'running'::text CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  created_by uuid,
  engine_version text NOT NULL DEFAULT 'health-assessment-v1'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  CONSTRAINT health_assessment_runs_pkey PRIMARY KEY (id),
  CONSTRAINT health_assessment_runs_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT health_assessment_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.health_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  assessment_run_id uuid NOT NULL,
  animal_id uuid NOT NULL,
  health_status text NOT NULL CHECK (health_status = ANY (ARRAY['healthy'::text, 'watch'::text, 'at_risk'::text, 'critical'::text])),
  health_score integer NOT NULL CHECK (health_score >= 0 AND health_score <= 100),
  risk_level text NOT NULL CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  confidence_score numeric NOT NULL DEFAULT 0 CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  confidence_label text NOT NULL DEFAULT 'Low'::text CHECK (confidence_label = ANY (ARRAY['High'::text, 'Medium'::text, 'Low'::text])),
  summary text NOT NULL,
  recommended_action text NOT NULL,
  source text NOT NULL DEFAULT 'rule_based'::text CHECK (source = ANY (ARRAY['rule_based'::text, 'statistical'::text, 'ml_model'::text, 'manual'::text])),
  engine_version text NOT NULL DEFAULT 'health-assessment-v1'::text,
  signals jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT health_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT health_assessments_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT health_assessments_assessment_run_id_fkey FOREIGN KEY (assessment_run_id) REFERENCES public.health_assessment_runs(id),
  CONSTRAINT health_assessments_animal_id_fkey FOREIGN KEY (animal_id) REFERENCES public.animals(id)
);
CREATE TABLE public.report_normalization_factors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  farm_id uuid NOT NULL,
  species_id uuid,
  carcass_to_live_ratio numeric NOT NULL DEFAULT 0.6200 CHECK (carcass_to_live_ratio > 0::numeric AND carcass_to_live_ratio <= 1.5),
  per_head_to_live_factor numeric NOT NULL DEFAULT 1.0000 CHECK (per_head_to_live_factor > 0::numeric AND per_head_to_live_factor <= 10::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_normalization_factors_pkey PRIMARY KEY (id),
  CONSTRAINT report_normalization_factors_farm_id_fkey FOREIGN KEY (farm_id) REFERENCES public.farms(id),
  CONSTRAINT report_normalization_factors_species_id_fkey FOREIGN KEY (species_id) REFERENCES public.animal_species(id),
  CONSTRAINT report_normalization_factors_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);